models/Clients.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "clients".
 *
 * @property int $id
 * @property string $name
 * @property string $email
 */
class Clients extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'clients';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'email'], 'required'],
            [['name', 'email'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'Email',
        ];
    }

    /**
     * {@inheritdoc}
     * @return ClientsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ClientsQuery(get_called_class());
    }
}

models/_Clients.php
<?php

namespace app\models;
use  yii\db\ActiveRecord;


class Clients extends ActiveRecord
{
     /**
     * <b>tableName</b> Método estático que retorna o nome da tabela
     * @return string table
     */
    public static function tableName()
    {
        return 'clients';
    } 

    /**
     * <b>rules</b> Método responsável por realizar a validação dos dados recebidos, 
     * OBS: O tipo safe, informa que as colunas que podem ser informado os dados do formulário (Massive Assignment) atribuição da massiva
     */

     public function rules()
     {
         //informa que os dados podem ser gravados ao utilizar o   $model->attributes no controller
         return [
            [['name', 'email'], 'safe'],
            [['name', 'email'], 'required'],
            [['name', 'email'], 'string', 'max' => 255], 
         ];
     }
}

controllers/ClientsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Clients;
use app\models\ClientsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientsController implements the CRUD actions for Clients model.
 */
class ClientsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Clients models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Clients model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Clients model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Clients();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Clients model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Clients model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Clients model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Clients the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Clients::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/_ClientsController.php
<?php

namespace app\controllers;

use app\models\Clients;
use yii\web\NotFoundHttpException;

class ClientsController extends \yii\web\Controller
{

     /**
     * <b>actionIndex</b> Método responsável por realizar a listagem dos clientes
     */

    public function actionIndex()
    {
        $clients = Clients::find()->all();

        return $this->render('index', [
            'clients' => $clients
        ]);
    }


    /**
     * <b>actionCreate</b> Método responsável por realizar a criação de um novo cliente.
     * OBS: Para utilizar $model->attributes, deverá estar habilitado no model dentro do metodo rules os nomes do campo com o valor safe
     */
    public function actionCreate()
    {
        $request = \yii::$app->request;

        if($request->isPost)
        {
           $model = new Clients();

           //attributes é uma propriedade do active record ao passar $request->post() sem parametro exemplo $request->post('email') nem nada ele irá pegar todos os dados do post
           $model->attributes =  $request->post(); 
           //só grava se o metodo rules existir no modelo
           $model->save();           
           return $this->redirect(['clients/index']);

        }

        return $this->render('create');
    }


      /**
     * <b>actionUpdate</b> Método responsável em realizar a atualização do cliente, recebe o id como parametro (antes disso devera registrar a 
     * personalização de rota no arquivo config/web.php) dentro do array rules
     */
    public function actionUpdate($id)
    {
        $model = Clients::findOne($id);

        if(! $model)
        {
            throw new NotFoundHttpException("Página não encontrada");
        }

        $request = \yii::$app->request;
        
        if($request->isPost)
        {
           //attributes é uma propriedade do active record ao passar $request->post() sem parametro exemplo $request->post('email') nem nada ele irá pegar todos os dados do post
           $model->attributes =  $request->post(); 
           //irá identificar que o registro já existe
           $model->save();
           
           return $this->redirect(['clients/index']);

        }

        return $this->render('update', [
            'model' => $model
        ]);
    }


     /**
     * <b>actionDelete<b/> Método responsável por excluir um registro, recebe como parametro o id do mesmo como parametro. (antes disso devera registrar a 
     * personalização de rota no arquivo config/web.php) dentro do array rules 
     * 
     */
    public function actionDelete($id)
    {

        $model = Clients::findOne($id);

        if(! $model)
        {
            throw new NotFoundHttpException("Página não encontrada");
        }

        $model->delete();
        
        return $this->redirect(['clients/index']);
    }




}

views/_clients/create.php
<?php
    /* @var $this yii\web\View */
    use yii\helpers\Url;
   
?>
<h1>Novo Cliente</h1>


<form name="form" method="post" action="<?= Url::to(['clients/create']); ?>">

   <input type="hidden" name="<?= \yii::$app->request->csrfParam; ?>" 
            value="<?= \yii::$app->request->csrfToken; ?>">

    <div class="form-group">
        <label for="name">Nome:</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Informe o nome">
    </div>
    <div class="form-group">
        <label for="email">email:</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Informe o email">
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

views/_clients/index.php
<?php
    use yii\helpers\Url;
    /* @var $this yii\web\View */
?>
<h1 class="text text-center">Clientes</h1>

<a href="<?= Url::to(['clients/create']);?>" class="btn btn-success">Novo Cliente</a>

<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Nome</th>
        <th>Email</th>
        <th>-</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach($clients as $client): ?>
            <tr>
                <td><?= $client->id; ?></td>
                <td><?= $client->name; ?></td>
                <td><?= $client->email; ?></td>
                <td>
                    <a href="<?= Url::to(['clients/update', 'id' => $client->id]);?>">Editar</a> |
                    <a href="<?= Url::to(['clients/delete', 'id' => $client->id]);?>">Excluir</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

views/_clients/update.php
<?php
    /* @var $this yii\web\View */
    use yii\helpers\Url;
?>
<h1>Atualizar Cliente</h1>


<form name="form" method="post" action="<?= Url::to(['clients/update', 'id' => $model->id]); ?>">

   <input type="hidden" name="<?= \yii::$app->request->csrfParam; ?>" 
            value="<?= \yii::$app->request->csrfToken; ?>">

    <div class="form-group">
        <label for="name">Nome:</label>
        <input type="text" class="form-control" id="name" name="name" 
                placeholder="Informe o nome" value="<?= $model->name; ?>">
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" id="email" name="email"
                placeholder="Informe o email" value="<?= $model->email; ?>">
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>